include:
  - project: 'iopsys/gitlab-ci-pipeline'
    file: '/static-code-analysis.yml'

stages:
    - static_code_analysis
    - compile_test
#    - checkpatch
#    - functional_test

variables:
  DEBUG: 'TRUE'
  SOURCE_FOLDER: "."
  RUN_CPPCHECK: "cppcheck --enable=all --error-exitcode=1 --suppress=unusedFunction --suppress=unreadVariable --suppress=variableScope --inline-suppr ."

run_compile_test:
    stage: compile_test
    image: iopsys/code-analysis
    allow_failure: false
    script:
        - "./gitlab-ci/install-dependencies.sh"
        - "./gitlab-ci/compile-warns.sh"

    artifacts:
        when: always
        paths:
            - functional-test-coverage.xml
            - timestamp.log
            - coverage.tar.gz
#run_functional_test:
#    stage: functional_test
#    image: iopsys/code-analysis-dev
#    allow_failure: false
#    script:
#        - "./gitlab-ci/install-dependencies.sh"
#        - "./gitlab-ci/setup.sh"
#        - "./gitlab-ci/functional-test.sh"
#
#    artifacts:
#        when: always
#        paths:
#            - functional-test-coverage.xml
#            - timestamp.log
#            - coverage.tar.gz

#run_checkpatch:
#    stage: checkpatch
#    image: iopsys/code-analysis-dev
#    allow_failure: false
#    script:
#        - "./gitlab-ci/coding-style.sh"
#
#    artifacts:
#        when: always
#        paths:
#            - functional-test-coverage.xml
#            - timestamp.log
#            - coverage.tar.gz
